Add-controllers
ACKAPOB/java-shareit pull request #1
Opened 2022-09-23 13:15 UTC by ACKAPOB

Postman Test is OK! ver 1.0

2022-09-24 04:18 UTC, eugene-lenkevich requested changes
Привет, Игорь, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-09-24 04:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @EqualsAndHashCode.Include // Непонятно как Item сравнивать, поусть пока что будет только по имени
На самом деле достаточно (и лучше всего) сравнивать только по идентификатору, именно поле id однозначно идентифицирует объект в нашем хранилище (в мапе)

2022-09-24 04:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @EqualsAndHashCode.Exclude
А id  за что исключен :)

2022-09-24 04:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    long id = 0;
А пусть тоже будет private :)

2022-09-24 04:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    public UserServiceImpl(UserStorage userStorage, UserMapper userMapper) {
Можно просто воткнуть аннотацию @RequiredArgsConstructor и не писать конструктор руками, к тому же ты уже используешь эту аннотацию, пусть лучше все будет единообразно :)

2022-09-24 04:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User out : userStorage.getUsers()) {
То де самое но через стримы :)

return userStorage.getUsers().stream().map(userMapper::toUserDto).collect(toList());

2022-09-24 04:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageImpl.java
> +        if (item.getName() != null) {
В данном случае это бизнес логика - логика обновления полей сущности. Storage же у нас отвечает за хранение данных. 
Лучше всего подобные вещи делать в сервисе, в хранилище же только ответственно за непосредственное сохранение записи. Так архитектурно более правильно, мы разграничиваем зоны ответственности. Иначе получается что бизнес-логика у нас расщеплена по нескольким классам. В будущем, допустим мы захотим использовать другой сторедж, который по другому хранит наши записи, но у нас не получится, обновление перестанет работать :) 

Это пример высокой связанности

https://habr.com/ru/company/otus/blog/505852/

В других хранилищах я видел что так же :)

2022-09-25 05:51 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @EqualsAndHashCode.Include // Непонятно как Item сравнивать, поусть пока что будет только по имени
Поправил! сравниваю только по id;

2022-09-25 05:55 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @EqualsAndHashCode.Exclude
Убрал исключение!

2022-09-25 05:56 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    long id = 0;
Поправил!

2022-09-25 05:57 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    public UserServiceImpl(UserStorage userStorage, UserMapper userMapper) {
Поправил!

2022-09-25 06:00 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User out : userStorage.getUsers()) {
Переделал!

2022-09-25 06:09 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User out : userStorage.getUsers()) {
В ItemServiceImpl тоже переделал по аналогии

2022-09-25 09:42 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageImpl.java
> +        if (item.getName() != null) {
Поправил!

2022-09-25 18:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User out : userStorage.getUsers()) {
На самом деле и так и так правильно, но через стримы сейчас "модно". Такая вот мода на функциональное программирование :)

2022-09-25 18:24 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-09-27 12:04 UTC, merged