Add bookings
ACKAPOB/java-shareit pull request #2
Opened 2022-10-11 08:44 UTC by ACKAPOB

2022-10-13 18:25 UTC, eugene-lenkevich requested changes
Привет, Игорь, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-10-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER,
Для @ManyToOne это значенеи fetch = FetchType.EAGER установливается по умолчанию, можно дополнительно  не указывать :)

2022-10-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    @Transactional
Обычно аннотируют не интерфейс, а конкретный класс, BookingServicImpl, это все таки больше про жетали реализации :)

К тому же в реализации уже есть эта аннотация 

https://stackoverflow.com/questions/5551541/where-to-put-transactional-in-interface-specification-or-implementation

2022-10-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Если стоит аннотация @Component то у методов стоит убрать static, иначе в этом всем нету смысла, статические методы можно вызывать и без экзмепляра класса :)

2022-10-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  @Data
У @Data есть особенность - помимо прочего генерируется equals и hashCode

Вообще, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Так что эти методы лучше определять каким то образом вручную а не полагаться а эту аннотацию :)

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
https://habr.com/ru/post/268903/

2022-10-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/service/impl/ItemRequestServiceImpl.java
> +        if (user.isEmpty()) {
а не проще записать как то так :)
User user = userRepository.findById(idUser.get()).orElseThrow(...)

2022-10-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/service/impl/ItemRequestServiceImpl.java
> +    public List<ItemRequestDto> getItemRequestPageable(Optional<Long> idUser,
Тут коннечно особых правил нет, но не слишком ли много Optional, в качестве параметров можно и обчные переменные передавать. Иначе как то громоздко получается. 
В принципе ничего трудного нет с тем чтобы сравнивать объекты с null. Иначе постоянно приходится дергать .get() и пр

В жавакодах на сам Optional написано что он предназначен для использования как объект, который возвращается из метода
![image](https://user-images.githubusercontent.com/94845100/195676235-a00a5d91-f520-4755-850e-2a8d9560fb26.png)

https://ru.stackoverflow.com/questions/731432/Где-имеет-смысл-использовать-optional

2022-10-14 07:25 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    @Transactional
Поправил!

2022-10-14 07:25 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER,
Исправил

2022-10-14 07:25 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Поправил!

2022-10-14 07:40 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/requests/service/impl/ItemRequestServiceImpl.java
> +        if (user.isEmpty()) {
Поправил! Подобным образом в классе BookingServiceImpl реализовал!

2022-10-14 08:00 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/requests/service/impl/ItemRequestServiceImpl.java
> +    public List<ItemRequestDto> getItemRequestPageable(Optional<Long> idUser,
Поправил! Хотел с Optional поиграться ))!

2022-10-14 08:00 UTC, ACKAPOB commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  @Data
Заменил @Data на  @Getter @Setter @ToString

2022-10-14 10:46 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/service/impl/ItemRequestServiceImpl.java
> +    public List<ItemRequestDto> getItemRequestPageable(Optional<Long> idUser,
Так и подумал, вообще конечно все подобные темы достаточно холиварны, лучше всегда оттакливаться от удобства чтения кода, ну или от того как принято в команде :)

2022-10-14 10:46 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/service/impl/ItemRequestServiceImpl.java
> +        if (user.isEmpty()) {
Ага, пусто будет единообразно :)

2022-10-14 10:52 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-10-14 10:52 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
@Transactional кстати можно было и оставить :)
Этими аннотациями мы определяем границы логических транзакций, изх пока особо не просят вроде как, но можно ставить на все публичные методы сервисов, в которых происходит изменение данных (create, update и delete)

Если интересно то вроде вот годная статья
https://habr.com/ru/post/682362/

2022-10-20 14:18 UTC, merged